### Site Basics
title: Eibhlín F. O'Dwyer
description: music | linguistics | fiction | gender | linux
author: "Eibhlín O'Dwyer"

baseurl: ""
url: "https://efod.co.uk"
email: website@beod.co.uk

### Jekyll Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
  - jekyll-feed

### Social Media Handles
bluesky: "eibhei.beod.co.uk"
github: "eibhei"
instagram: "eibhei"
mastodon: "@0d_billie"

### Publishing Settings
show_drafts: false
future: false
timezone: Europe/London

### Site Settings
# Markdown
highlighter: rouge
markdown: kramdown
sass:
  sass_dir: /assets/css/_sass
  style: compressed

# Page Settings
collections:
  projects:
    output: true
    permalink: /projects/:name/
    order:
      - minimalistBookClub.md
exclude:
  - README.md
  - LICENSE.md
include:
  - _pages

# Blog Settings
paginate: 10
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/
feed:
  excerpt_only: true

# Optimisation settings
compress_html:
  clippings:
    [
      html,
      div,
      p,
      ul,
      td,
      h1,
      h2,
      h3,
      h4,
      link,
      meta,
      footer,
      nav,
      img,
      header,
      hr,
      br,
      head,
      style,
      li,
      ul,
      ol,
      time,
      main,
      script,
      title,
    ]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []
