matrix:
- name: Markdown
  aspell:
    lang: en
    d: en_GB
  dictionary:
    encoding: utf-8
    wordlists:
      - .github/workflows/config/spellcheck_wordlist.txt
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
  sources:
  - "_posts/*.md"
  - "_pages/*.md"
  - "index.md"
  default_encoding: utf-8